import { z } from 'zod';

export const LayerSummarySchema = z.object({
  id: z.string(),
  label: z.string(),
  file_count: z.number().int(),
  symbol_count: z.number().int(),
});

export const SnapshotSchema = z.object({
  id: z.string().uuid().optional(), // Generated by DB
  project_id: z.string().uuid().optional(), // Set when saving to cloud
  schema_version: z.string().default('1.0.0'),
  snapshot_number: z.number().int().optional(),

  // Git context
  commit_sha: z.string().nullable().optional(),
  commit_message: z.string().nullable().optional(),
  branch: z.string().nullable().optional(),

  // Summary metrics
  total_files: z.number().int().default(0),
  total_symbols: z.number().int().default(0),
  total_edges: z.number().int().default(0),
  total_loc: z.number().int().default(0),
  languages: z.array(z.string()).default([]),
  framework: z.string().nullable().optional(),
  layer_summary: z.array(LayerSummarySchema).default([]),

  // Health scores
  coupling_score: z.number().nullable().optional(),
  complexity_score: z.number().nullable().optional(),
  modularity_score: z.number().nullable().optional(),

  // Analysis metadata
  analysis_duration_ms: z.number().int().optional(),
  analyzer_version: z.string().optional(),
  trigger: z.enum(['manual', 'push', 'schedule', 'api']).default('manual'),

  analyzed_at: z.string().datetime().optional(),
});

export type Snapshot = z.infer<typeof SnapshotSchema>;
